# Generated by Django 5.0.3 on 2024-03-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verifild',
            new_name='is_verified',
        ),
    ]
